stages:
  - build-lab
  - deploy-lab
  - build-prod
  - deploy-prod

workflow:
  rules:
    # Do not run pipeline on MR
    - if: $CI_PIPELINE_SOURCE != 'merge_request_event'

include:
  - project: 'infrastructure/pipelines'
    ref: main
    file: 'helper/docker.yml'
  - project: 'infrastructure/pipelines'
    ref: main
    file: '/deploy/swarm-base.yml'

variables:
  DEFAULT_MAIN_BRANCH: master
  DIST_FOLDER: _site/
  NODE_IMAGE: ${CI_DEPENDENCY_PROXY_GROUP_IMAGE_PREFIX}/node:lts

build_lab:
  stage: build-lab
  tags:
      - build
      - docker
  script:
    - !reference [.helper-check-deploy-token, script]
    - !reference [.helper-registry-login-job-token, script]
    - !reference [.helper-registry-login-hub, script]
    - !reference [.helper-registry-login-proxy, script]

    - docker build --no-cache --build-arg NODE_ENV=lab -t $DEFAULT_CI_REGISTRY_IMAGE:lab-$CI_COMMIT_SHA .
    - docker push $DEFAULT_CI_REGISTRY_IMAGE:lab-$CI_COMMIT_SHA

build_prod:
  stage: build-prod
  tags:
      - build
      - docker
  rules:
    - if: $CI_COMMIT_BRANCH == $DEFAULT_MAIN_BRANCH
      when: on_success
    - when: never

  script:
    - !reference [.helper-check-deploy-token, script]
    - !reference [.helper-registry-login-job-token, script]
    - !reference [.helper-registry-login-hub, script]
    - !reference [.helper-registry-login-proxy, script]

    - docker build --no-cache --build-arg NODE_ENV=prod -t $DEFAULT_CI_REGISTRY_IMAGE:prod-$CI_COMMIT_SHA .
    - docker push $DEFAULT_CI_REGISTRY_IMAGE:prod-$CI_COMMIT_SHA

deploy_lab:
  extends: .deploy_swarm
  stage: deploy-lab
  needs:
    - job: build_lab
  tags:
    - swarm
    - deploy
    - cda
    - lab
  variables:
    PREVIOUS_IMAGE_TAG: lab-$CI_COMMIT_SHA
    IMAGE_TAG: lab-$CI_COMMIT_SHA
  rules:
    - if: $CI_COMMIT_BRANCH
      when: on_success
  environment:
    name: lab
    url: https://${DOMAIN}/${DEFAULT_CI_PROJECT_NAME}

deploy_prod:
  extends: .deploy_swarm
  stage: deploy-prod
  needs :
    - job: build_prod
  tags:
    - swarm
    - deploy
    - cda
    - prod
  variables:
    PREVIOUS_IMAGE_TAG: prod-$CI_COMMIT_SHA
    IMAGE_TAG: prod-$CI_COMMIT_SHA
  rules:
    - if: $CI_COMMIT_REF_NAME != $DEFAULT_MAIN_BRANCH
      when: never
    - when: manual
      allow_failure: true
